spring:
  application:
    name: chat-backend
    file-storage:
      local-path: ${FILE_STORAGE_PATH:./uploads}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/chatdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    show-sql: false

  flyway:
    enabled: false
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:20MB}
      max-request-size: ${MAX_REQUEST_SIZE:20MB}

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  issuer: ${JWT_ISSUER:jace}
  access-token-ttl: ${JWT_ACCESS_TTL:PT15M}
  refresh-token-ttl: ${JWT_REFRESH_TTL:P7D}
  secret: ${JWT_SECRET:YmFzZTY0LXNlY3JldC1rZXktZm9yLWRldi10ZXN0aW5nLXNob3VsZC1iZS1hdC1sZWFzdC0zMmJ5dGVzLWxvbmc=}
